package edu.missouristate.aianalyzer.utility.ai;

import com.google.genai.Client;
import com.google.genai.types.Content;
import com.google.genai.types.GenerateContentResponse;
import com.google.genai.types.Part;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.concurrent.CompletableFuture;

import static edu.missouristate.aianalyzer.utility.ai.ReadFileUtil.*;

/**
 * Utility service that communicates with the Google Gemini AI model to perform
 * text, file, and image-based analysis. This class provides methods for summarizing
 * file content, handling large file uploads, and generating image classification responses.
 */
@Service
@RequiredArgsConstructor
public class AiQueryUtil {

    /** Client instance used for all Gemini model requests. */
    private final Client client;

    /**
     * Sends the entire file content directly to Gemini for summarization.
     *
     * This method is used for small files whose contents can safely be read
     * entirely into memory. It returns a single sentence of up to 40 words
     * summarizing the file contents.
     *
     * @param file The complete file contents as a string.
     * @return A summary generated by the Gemini model.
     */
    public String activeResponseFromFile(String file) {
        CompletableFuture<GenerateContentResponse> responseFuture =
                client.async.models.generateContent(
                        "gemini-2.0-flash",
                        "Provide a single, up to 40-word sentence summarizing the main point or summary of the following file content. "
                                + file,
                        null);

        return responseFuture
                .thenApply(GenerateContentResponse::text)
                .join();
    }

    /**
     * Sends a URI reference to a large file stored remotely to Gemini for analysis.
     *
     * This method is used when the file is too large to read into memory. The file
     * is referenced by URI and labeled with its interpretation type.
     *
     * @param file A URI path pointing to the uploaded file.
     * @param fileInterpretation The interpretation type (for example, text/plain).
     * @return A summary of the remote file's contents, limited to about 40 words.
     */
    public String activeResponseFromLargeFile(String file, String fileInterpretation) {
        Content content = Content.fromParts(
                Part.fromText("Provide a single, up to 40-word sentence summarizing the main point or summary of the following file content."),
                Part.fromUri(file, fileInterpretation));

        CompletableFuture<GenerateContentResponse> responseFuture =
                client.async.models.generateContent(
                        "gemini-2.0-flash",
                        content,
                        null);

        return responseFuture
                .thenApply(GenerateContentResponse::text)
                .join();
    }

    /**
     * Analyzes an image and determines whether it contains a single human face,
     * two faces, a group of three or more faces, or no human faces at all.
     *
     * If no human faces are detected, the method returns a description of what was photographed.
     *
     * @param image A URI reference to the uploaded image.
     * @param fileInterpretation The image type (such as image/jpeg).
     * @return One of the following: "single", "two", "group", or a description of what is in the photo.
     * @throws IOException If the image reference cannot be read.
     */
    public String respondWithImageCategory(String image, String fileInterpretation) throws IOException {
        Content content = Content.fromParts(
                Part.fromText("Provide the word single or two based on the amount of human faces in this photo if its a" +
                        "group provide the word description sport, hiking, cooking, event, or gathering. If there are not human faces respond with" +
                        "a word describing the contents of the photo such as landscape, food, or miscellaneous."),
                Part.fromUri(image, fileInterpretation));

        CompletableFuture<GenerateContentResponse> responseFuture =
                client.async.models.generateContent(
                        "gemini-2.0-flash",
                        content,
                        null);

        return responseFuture
                .thenApply(GenerateContentResponse::text)
                .join();
    }

    /**
     * Reads a small file into memory and sends its contents to Gemini for summarization.
     *
     * This method is used only for files whose size does not exceed the configured
     * maximum threshold for in-memory processing.
     *
     * @param filePath The filesystem path to the small file.
     * @param fileType The file type or extension.
     * @return A summary string from the AI, or an error message.
     * @throws IOException If the file cannot be read.
     */
    public String processSmallFileAIResponse(Path filePath, String fileType) throws IOException {
        try {
            String fileContent = readFileAsString(filePath, fileType);
            return activeResponseFromFile(fileContent);
        } catch (IOException e) {
            return "Error processing file: " + e.getMessage();
        }
    }

    /**
     * Processes large files by uploading them to Google Cloud Storage and
     * passing their URI reference to Gemini for remote analysis.
     *
     * This method avoids loading large files into memory and instead relies on
     * Gemini's ability to read the file from cloud storage.
     *
     * @param filePath The path to the large file on disk.
     * @param fileType The detected or provided file type.
     * @return A summary from Gemini or an error message.
     * @throws IOException If the file cannot be uploaded or processed.
     */
    public String processLargeFileAIResponse(Path filePath, String fileType) throws IOException {
        if (!Files.exists(filePath)) {
            return "File does not exist: " + filePath;
        }

        try {
            Path parentDir = filePath.getParent();
            String newFileName = filePath.getFileName().toString().replaceFirst("\\.[^.]+$", ".txt");
            Path newFilePath = parentDir.resolve(newFileName).toAbsolutePath();

            uploadFile(filePath, fileType);

            return activeResponseFromLargeFile(
                    "gs://aianalyser/files" + newFilePath,
                    readDocumentType(fileType)
            );

        } catch (IOException e) {
            return "Error processing file: " + e.getMessage();
        }
    }
}
